---
title: "CT ANES Analysis"
author: "Ryan Burge"
date: "April 21, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(readr)
library(broom)
library(Hmisc)
library(forcats)
library(haven)
library(dplyr)
library(ggplot2)
library(extrafont)
library(car)
library(scales)
library(gridExtra)
anes <- read_dta("D:/anes_2016/anes_timeseries_2016.dta")
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
anes <- read_dta("D:/anes_2016/anes_timeseries_2016.dta")


anes$bagain <- Recode(anes$V161263, "1=1; else=0")

anes$prot <- Recode(anes$V161247a, "1=1; else=0")

anes$white <- Recode(anes$V161310a, "1=1; else =0")
anes$black <- Recode(anes$V161310b, "1=1; else =0")
anes$asian <- Recode(anes$V161310d, "1=1; else =0")

anes$whtbaprot <- anes$white + anes$bagain + anes$prot
anes$whtbaprot <- Recode(anes$whtbaprot, "3=1; else=0")

anes$whtnonba <- anes$white + anes$prot
anes$whtnonba <- Recode(anes$whtnonba, "2=1; else=0")
anes$batest <- Recode(anes$bagain, "1=10; else=0")
anes$whtnonba <- anes$whtnonba + anes$batest
anes$whtnonba <- Recode(anes$whtnonba, "1=1; else=0")

anes$attend <-  anes$V161245
anes$attend <- Recode(anes$attend, "-9=0; -1=0; 1=6; 2=4; 3=3; 4=2; 5=1")

anes$hiattend <- Recode(anes$V161245a, "1=-1; else=0")
anes$attend <- anes$hiattend + anes$attend

anes$catholic <- Recode(anes$V161247a, "2=1; else=0")
anes$jewish <- Recode(anes$V161247a, "3=1; else=0")

anes$blackprot <- anes$black + anes$prot
anes$blackprot <- Recode(anes$blackprot, "2=1; else=0")

anes$r1 <- Recode(anes$whtbaprot, "1=1; else=0")
anes$r2 <- Recode(anes$whtnonba, "1=2; else=0")
anes$r3 <- Recode(anes$blackprot, "1=3; else=0")
anes$r4 <- Recode(anes$catholic, "1=4; else=0")
anes$r5 <- Recode(anes$jewish, "1=5; else=0")

anes$reltrad <- anes$r1 + anes$r2 + anes$r3 + anes$r4 + anes$r5

anes$reltrad <- Recode(anes$reltrad, "1='White Born Again Protestants';
                       2='White Non Born Again Protestants';
                       3='Black Protestants';
                       4='Catholic'; 
                       5='Jewish';
                       0= 'Other'")
```

## Simple Vote Totals 

```{r message=FALSE, warning=FALSE, echo=FALSE}
anes$vote16 <- anes$V162062x

votetotal <- anes %>% filter(white ==1 & prot ==1 & bagain ==1) %>% 
  count(vote16, wt = V160102) %>% mutate(weight = prop.table(n)) %>% arrange(desc(weight))

votetotal$vote16 <-as.numeric(votetotal$vote16)

votetotal$vote16 <- Recode(votetotal$vote16,"1='Hillary Clinton';
                       2='Donald Trump';
                       3='Gary Johnson';
                       4='Jill Stein'; 
                       5='Other Candidate';
                      -1= 'No Vote';
                      -9='Refused'")

ggplot(votetotal, aes(x=reorder(vote16, -weight), y= weight*100)) + geom_col()
```

## Thermometer Scores for Each Candidate

```{r message=FALSE, warning=FALSE, echo=FALSE}
anes$trumptherm <- anes$V162079
anes$trumptherm[anes$trumptherm == -9] <- NA
anes$trumptherm[anes$trumptherm == -7] <- NA
anes$trumptherm[anes$trumptherm == -6] <- NA
anes$trumptherm[anes$trumptherm == 998] <- NA

anes$clintontherm <- anes$V162078
anes$clintontherm[anes$clintontherm == -9] <- NA
anes$clintontherm[anes$clintontherm == -7] <- NA
anes$clintontherm[anes$clintontherm == -6] <- NA
anes$clintontherm[anes$clintontherm == 998] <- NA

anes$hrccut <- as.numeric(cut2(anes$clintontherm, g=3))
anes$djtcut <- as.numeric(cut2(anes$trumptherm, g=3))

whtbaprot <- filter(anes, whtbaprot ==1)


t1 <- table(whtbaprot$hrccut)
t1 <- tidy(t1)

t1$Var1 <- Recode(t1$Var1, "1='0-33';
                            2='34-66';
                            3='67-100'")

t1 <- t1 %>% mutate(pct = round(Freq/sum(Freq),2))

ggplot(t1, aes(x=Var1, y=pct*100)) + geom_col(fill = "dodgerblue3", color = "black") + 
  xlab("Clinton Thermometer Scores") + ylab("Percent of Respondents") + ggtitle("Among White Born Again Protestants") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) 


t2 <- table(whtbaprot$djtcut)
t2 <- tidy(t2)

t2 <- t2 %>% mutate(pct = round(Freq/sum(Freq),2))

t2$Var1 <- Recode(t2$Var1, "1='0-33';
                            2='34-66';
                            3='67-100'")

ggplot(t2, aes(x=Var1, y=pct*100)) + geom_col(fill = "firebrick2", color = "black") + 
  xlab("Trump Thermometer Scores") + ylab("Percent of Respondents") + ggtitle("Among White Born Again Protestants") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans"))
```

## How do voters perceive the candidates on abortion? 

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12}
anes$hrcabort <- anes$V162181
anes$djtabort <- anes$V162182

anes$hrcabort[anes$hrcabort == -9] <- NA
anes$hrcabort[anes$hrcabort == -7] <- NA
anes$hrcabort[anes$hrcabort == -6] <- NA
anes$hrcabort[anes$hrcabort == -8] <- NA

anes$djtabort[anes$djtabort == -9] <- NA
anes$djtabort[anes$djtabort == -7] <- NA
anes$djtabort[anes$djtabort == -6] <- NA
anes$djtabort[anes$djtabort == -8] <- NA

whtbaprot <- filter(anes, whtbaprot ==1)

t1 <- table(anes$hrcabort)
t2 <- table(whtbaprot$hrcabort)

t1 <- tidy(t1)
t2 <- tidy(t2)

t1$Var1 <- Recode(t1$Var1, "1='Complete Ban';
                            2='Rape, Incest, Life of the Mother';
                            3='Clearly Established Need';
                            4='Always Permitted'")

t2$Var1 <- Recode(t2$Var1, "1='Complete Ban';
                            2='Rape, Incest, Life of the Mother';
                            3='Clearly Established Need';
                            4='Always Permitted'")

t1 <- t1 %>% mutate(pct = round(Freq/sum(Freq),2))
t2 <- t2 %>% mutate(pct = round(Freq/sum(Freq),2))

t1$label  <- c("Entire Sample")
t2$label  <- c("BA + Prot")

hrcabort <- rbind(t1, t2)

hrcabort$Var1 <- factor(hrcabort$Var1, levels=unique(hrcabort$Var1))


ggplot(hrcabort, aes(1, pct*100)) + geom_col(aes(fill= Var1), colour = "black") +
  xlab("Abortion Scenarios") + ylab("Percent of Respondents") + ggtitle("Perception of Clinton on Abortion") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + coord_flip() + theme(axis.title.y = element_blank()) + 
  theme(axis.ticks = element_blank(), axis.text.y = element_blank()) + theme(legend.position="bottom") +  
  guides(fill = guide_legend(reverse = TRUE)) + labs(fill="")+ facet_grid(label ~ .)  


t1 <- table(anes$djtabort)
t2 <- table(whtbaprot$djtabort)

t1 <- tidy(t1)
t2 <- tidy(t2)

t1$Var1 <- Recode(t1$Var1, "1='Complete Ban';
                            2='Rape, Incest, Life of the Mother';
                            3='Clearly Established Need';
                            4='Always Permitted'")

t2$Var1 <- Recode(t2$Var1, "1='Complete Ban';
                            2='Rape, Incest, Life of the Mother';
                            3='Clearly Established Need';
                            4='Always Permitted'")

t1 <- t1 %>% mutate(pct = round(Freq/sum(Freq),2))
t2 <- t2 %>% mutate(pct = round(Freq/sum(Freq),2))

t1$label  <- c("Entire Sample")
t2$label  <- c("BA + Prot")

djtabort <- rbind(t1, t2)

djtabort$Var1 <- factor(djtabort$Var1, levels=unique(djtabort$Var1))


ggplot(djtabort, aes(1, pct*100)) + geom_col(aes(fill= Var1), colour = "black") +
  xlab("Abortion Scenarios") + ylab("Percent of Respondents") + ggtitle("Perception of Trump on Abortion") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + coord_flip() + theme(axis.title.y = element_blank()) + 
  theme(axis.ticks = element_blank(), axis.text.y = element_blank()) + theme(legend.position="bottom") +  
  guides(fill = guide_legend(reverse = TRUE)) + labs(fill="")+ facet_grid(label ~ .)  
```

## How do Evangelicals perceive discrimination? 

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=10}
anes$blackdis <- anes$V162357

anes$blackdis[anes$blackdis == -9] <- NA
anes$blackdis[anes$blackdis == -7] <- NA
anes$blackdis[anes$blackdis == -6] <- NA
anes$blackdis[anes$blackdis == -5] <- NA

anes$blackdis <- 6- anes$blackdis

anes$hispdis <- anes$V162358

anes$hispdis[anes$hispdis == -9] <- NA
anes$hispdis[anes$hispdis == -7] <- NA
anes$hispdis[anes$hispdis == -6] <- NA
anes$hispdis[anes$hispdis == -5] <- NA

anes$hispdis <- 6- anes$hispdis


anes$asiandis <- anes$V162359

anes$asiandis[anes$asiandis == -9] <- NA
anes$asiandis[anes$asiandis == -7] <- NA
anes$asiandis[anes$asiandis == -6] <- NA
anes$asiandis[anes$asiandis == -5] <- NA

anes$asiandis <- 6- anes$asiandis


anes$whitedis <- anes$V162360

anes$whitedis[anes$whitedis == -9] <- NA
anes$whitedis[anes$whitedis == -7] <- NA
anes$whitedis[anes$whitedis == -6] <- NA
anes$whitedis[anes$whitedis == -5] <- NA

anes$whitedis <- 6- anes$whitedis


anes$lgbtdis <- anes$V162361

anes$lgbtdis[anes$lgbtdis == -9] <- NA
anes$lgbtdis[anes$lgbtdis == -7] <- NA
anes$lgbtdis[anes$lgbtdis == -6] <- NA
anes$lgbtdis[anes$lgbtdis == -5] <- NA

anes$lgbtdis <- 6- anes$lgbtdis


anes$womendis <- anes$V162362

anes$womendis[anes$womendis == -9] <- NA
anes$womendis[anes$womendis == -7] <- NA
anes$womendis[anes$womendis == -6] <- NA
anes$womendis[anes$womendis == -5] <- NA

anes$womendis <- 6- anes$womendis


anes$mendis <- anes$V162363

anes$mendis[anes$mendis == -9] <- NA
anes$mendis[anes$mendis == -7] <- NA
anes$mendis[anes$mendis == -6] <- NA
anes$mendis[anes$mendis == -5] <- NA

anes$mendis <- 6- anes$mendis


anes$muslimdis <- anes$V162364

anes$muslimdis[anes$muslimdis == -9] <- NA
anes$muslimdis[anes$muslimdis == -7] <- NA
anes$muslimdis[anes$muslimdis == -6] <- NA
anes$muslimdis[anes$muslimdis == -5] <- NA

anes$muslimdis <- 6- anes$muslimdis


anes$xtndis <- anes$V162365

anes$xtndis[anes$xtndis == -9] <- NA
anes$xtndis[anes$xtndis == -7] <- NA
anes$xtndis[anes$xtndis == -6] <- NA
anes$xtndis[anes$xtndis == -5] <- NA

anes$xtndis <- 6- anes$xtndis


anes$transdis <- anes$V162366

anes$transdis[anes$transdis == -9] <- NA
anes$transdis[anes$transdis == -7] <- NA
anes$transdis[anes$transdis == -6] <- NA
anes$transdis[anes$transdis == -5] <- NA

anes$transdis <- 6- anes$transdis


whtbaprot <- filter(anes, whtbaprot ==1)

t1 <- table(whtbaprot$blackdis)
t1 <- tidy(t1)
t1$group <- c("Blacks")
t1 <- t1 %>% mutate(pct = round(Freq/sum(Freq),2))


t2 <- table(whtbaprot$hispdis)
t2 <- tidy(t2)
t2$group <- c("Hispanics")
t2 <- t2 %>% mutate(pct = round(Freq/sum(Freq),2))

t3 <- table(whtbaprot$asiandis)
t3 <- tidy(t3)
t3$group <- c("Asians")
t3 <- t3 %>% mutate(pct = round(Freq/sum(Freq),2))

t4 <- table(whtbaprot$whitedis)
t4 <- tidy(t4)
t4$group <- c("Whites")
t4 <- t4 %>% mutate(pct = round(Freq/sum(Freq),2))

t5 <- table(whtbaprot$lgbtdis)
t5 <- tidy(t5)
t5$group <- c("Gay")
t5 <- t5 %>% mutate(pct = round(Freq/sum(Freq),2))

t6 <- table(whtbaprot$womendis)
t6 <- tidy(t6)
t6$group <- c("Women")
t6 <- t6 %>% mutate(pct = round(Freq/sum(Freq),2))


t7 <- table(whtbaprot$mendis)
t7 <- tidy(t7)
t7$group <- c("Men")
t7 <- t7 %>% mutate(pct = round(Freq/sum(Freq),2))

t8 <- table(whtbaprot$muslimdis)
t8 <- tidy(t8)
t8$group <- c("Muslims")
t8 <- t8 %>% mutate(pct = round(Freq/sum(Freq),2))

t9 <- table(whtbaprot$xtndis)
t9 <- tidy(t9)
t9$group <- c("Xtns")
t9 <- t9 %>% mutate(pct = round(Freq/sum(Freq),2))

t10 <- table(whtbaprot$transdis)
t10 <- tidy(t10)
t10$group <- c("Trans.")
t10 <- t10 %>% mutate(pct = round(Freq/sum(Freq),2))

dis <- rbind(t1, t2, t3, t4, t5, t6, t7, t8, t9, t10)

dis$Var1 <- Recode(dis$Var1, "1='None at all';
                  2='A little';
                  3='A moderate amount';
                  4='A lot';
                  5='A great deal'")

dis$Var1 <- factor(dis$Var1, levels=unique(dis$Var1))


ggplot(dis, aes(1, pct*100)) + geom_col(aes(fill= fct_rev(Var1)), colour = "black") +
  xlab("Abortion Scenarios") + ylab("Percent of Respondents") + ggtitle("Born Again Protestants Views on Discrimination") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(text=element_text(size=18, family="KerkisSans")) + coord_flip() + theme(axis.title.y = element_blank()) + 
  theme(axis.ticks = element_blank(), axis.text.y = element_blank()) + theme(legend.position="bottom") +  
  guides(fill = guide_legend(reverse = TRUE)) + labs(fill="")+ facet_grid(group ~ .)  
```

## How do the two candidates treat women? 

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=5}
anes$trumpwomen <- anes$V162188x
anes$clintonwomen <- anes$V162189x

anes$clintonwomen[anes$clintonwomen == -9] <- NA
anes$clintonwomen[anes$clintonwomen == -8] <- NA
anes$clintonwomen[anes$clintonwomen == -7] <- NA
anes$clintonwomen[anes$clintonwomen == -6] <- NA

anes$trumpwomen[anes$trumpwomen == -9] <- NA
anes$trumpwomen[anes$trumpwomen == -8] <- NA
anes$trumpwomen[anes$trumpwomen == -7] <- NA
anes$trumpwomen[anes$trumpwomen == -6] <- NA

clinton <- anes %>% group_by(reltrad) %>% summarise(mean = mean(clintonwomen, na.rm= TRUE))
clinton$label <- c("Clinton")

trump <- anes %>% group_by(reltrad) %>% summarise(mean = mean(trumpwomen, na.rm= TRUE))
trump$label <- c("Trump")

women <- rbind(clinton, trump)

ggplot(women, aes(x=mean, y =label)) + geom_point(color = "black", shape=21, size =4, aes(fill = factor(reltrad))) + 
  theme(legend.title=element_blank()) +
  theme(legend.position = "bottom") +
  scale_x_continuous(limits = c(1,7), breaks = c(1,2,3,4,5,6,7), labels = c("Extremely Poorly", "Moderately Poorly", "Slightly Poorly", "Neither", "Slightly Well", "Moderately Well", "Extremely Well")) +  
  scale_fill_manual(values = c("#866097","#365D25","#252F99","#00CCFF", "#FC009C", "#674E60")) + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("") + ylab("") + ggtitle("How Does Each Candidate Treat Women?") +
  theme(plot.title = element_text(hjust = 0.5))
```

##Do voters think the Trump video should matter? 


```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=3}
anes$trumpvid <- anes$V162127
anes$trumpvid <- Recode(anes$trumpvid, "1=5; 2=4; 3=3; 4=2; 5=1; else=0")

vid <- anes %>% group_by(reltrad) %>% summarise(mean = mean(trumpvid, na.rm = TRUE))
vid$label <- c("Trump Video")

ggplot(vid, aes(x=mean, y =label)) + geom_point(color = "black", shape=21, size =4, aes(fill = factor(reltrad))) + 
  theme(legend.title=element_blank()) +
  theme(legend.position = "bottom") +
  scale_x_continuous(limits = c(1,5), breaks = c(1,2,3,4,5), labels = c("Not at all", "A little", "A moderate amount", "A lot", "A great deal")) +  
  scale_fill_manual(values = c("#866097","#365D25","#252F99","#00CCFF", "#FC009C", "#674E60")) + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("") + ylab("") + ggtitle("Do you think the video should matter to voters?") +
  theme(plot.title = element_text(hjust = 0.5))

```

## Do you trust the voting process? 

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=3}
anes$trust_vote <- anes$V162219

anes$trust_vote[anes$trust_vote == -9] <- NA
anes$trust_vote[anes$trust_vote == -8] <- NA
anes$trust_vote[anes$trust_vote == -7] <- NA
anes$trust_vote[anes$trust_vote == -6] <- NA

anes$trust_vote <- 6 - anes$trust_vote

#anes$trust_vote <- Recode(anes$trust_vote, "1= 'Never';
     #                                       2= 'Some of the time';
      #                                      3= 'About half of the time';
     #                                       4= 'Most of the time';
      #                                      5= 'All of the time'")


trust <- anes %>% group_by(reltrad) %>% summarise(mean = mean(trust_vote, na.rm = TRUE))
trust$label <- c("Trust Voting Process")

ggplot(trust, aes(x=mean, y =label)) + geom_point(color = "black", shape=21, size =4, aes(fill = factor(reltrad))) + 
  theme(legend.title=element_blank()) +
  theme(legend.position = "bottom") +
  scale_x_continuous(limits = c(1,5), breaks = c(1,2,3,4,5), labels = c("Never", "Some of the time", "About half of the time", "Most of the time", "All of the time")) +  
  scale_fill_manual(values = c("#866097","#365D25","#252F99","#00CCFF", "#FC009C", "#674E60")) + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("") + ylab("") + ggtitle("How often are votes are counted fairly?") +
  theme(plot.title = element_text(hjust = 0.5))

```

## Traditional Gender Roles 

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=3}
anes$momwork <- anes$V162230

anes$momwork[anes$momwork == -9] <- NA
anes$momwork[anes$momwork == -8] <- NA
anes$momwork[anes$momwork == -7] <- NA
anes$momwork[anes$momwork == -6] <- NA

anes$momwork <- Recode(anes$momwork, "1=1; 2=-1; 3=0")

mom <- anes %>% group_by(reltrad) %>% summarise(mean = mean(momwork, na.rm = TRUE))

mom$label <- c("Mom Doesn't Work")

ggplot(mom, aes(x=mean, y =label)) + geom_point(color = "black", shape=21, size =4, aes(fill = factor(reltrad))) + 
  theme(legend.title=element_blank()) +
  theme(legend.position = "bottom") +
  scale_x_continuous(limits = c(-1,1), breaks = c(-1,0,1), labels = c("Worse", "Makes No Difference", "Better")) +  
  scale_fill_manual(values = c("#866097","#365D25","#252F99","#00CCFF", "#FC009C", "#674E60")) + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("") + ylab("") + ggtitle("If the Woman Stays Home is that:") +
  theme(plot.title = element_text(hjust = 0.5))

```

## Black Racial Resentment 

```{r message=FALSE, warning=FALSE, echo=FALSE, fig.width=12, fig.height=20}
anes$black1 <- anes$V162211
anes$black2 <- anes$V162212
anes$black3 <- anes$V162213
anes$black4 <- anes$V162214


anes$black1[anes$black1 == -9] <- NA
anes$black1[anes$black1 == -8] <- NA
anes$black1[anes$black1 == -7] <- NA
anes$black1[anes$black1 == -6] <- NA

anes$black2[anes$black2 == -9] <- NA
anes$black2[anes$black2 == -8] <- NA
anes$black2[anes$black2 == -7] <- NA
anes$black2[anes$black2 == -6] <- NA

anes$black3[anes$black3 == -9] <- NA
anes$black3[anes$black3 == -8] <- NA
anes$black3[anes$black3 == -7] <- NA
anes$black3[anes$black3 == -6] <- NA

anes$black4[anes$black4 == -9] <- NA
anes$black4[anes$black4 == -8] <- NA
anes$black4[anes$black4 == -7] <- NA
anes$black4[anes$black4 == -6] <- NA

anes$black1 <- 6- anes$black1
anes$black4 <- 6- anes$black4

anes$resent <- anes$black1 + anes$black2 + anes$black3 + anes$black4

anes$resent <- anes$resent/20


anes$bagain <- Recode(anes$V161263, "1=1; else=0")

anes$prot <- Recode(anes$V161247a, "1=1; else=0")

anes$white <- Recode(anes$V161310a, "1=1; else =0")
anes$black <- Recode(anes$V161310b, "1=1; else =0")
anes$asian <- Recode(anes$V161310d, "1=1; else =0")

anes$whtbaprot <- anes$white + anes$bagain + anes$prot
anes$whtbaprot <- Recode(anes$whtbaprot, "3=1; else=0")

anes$whtnonba <- anes$white + anes$prot
anes$whtnonba <- Recode(anes$whtnonba, "2=1; else=0")
anes$batest <- Recode(anes$bagain, "1=10; else=0")
anes$whtnonba <- anes$whtnonba + anes$batest
anes$whtnonba <- Recode(anes$whtnonba, "1=1; else=0")

anes$attend <-  anes$V161245
anes$attend <- Recode(anes$attend, "-9=0; -1=0; 1=6; 2=4; 3=3; 4=2; 5=1")

anes$hiattend <- Recode(anes$V161245a, "1=-1; else=0")
anes$attend <- anes$hiattend + anes$attend

anes$catholic <- Recode(anes$V161247a, "2=1; else=0")
anes$jewish <- Recode(anes$V161247a, "3=1; else=0")

anes$blackprot <- anes$black + anes$prot
anes$blackprot <- Recode(anes$blackprot, "2=1; else=0")

anes$r1 <- Recode(anes$whtbaprot, "1=1; else=0")
anes$r2 <- Recode(anes$whtnonba, "1=2; else=0")
anes$r3 <- Recode(anes$blackprot, "1=3; else=0")
anes$whtcath <- anes$catholic + anes$white
anes$r4 <- Recode(anes$whtcath, "2=4;else=0")
anes$whtjew <- anes$jewish + anes$white
anes$r5 <- Recode(anes$whtjew, "2=5; else=0")

anes$reltrad <- anes$r1 + anes$r2 + anes$r3 + anes$r4 + anes$r5

anes$reltrad <- Recode(anes$reltrad, "1='White Born Again Protestants';
                       2='White Non Born Again Protestants';
                       3='Black Protestants';
                       4='white Catholic'; 
                       5='White Jewish';
                       0= 'Other'")

resent <- anes %>% group_by(reltrad) %>% summarise(mean = mean(resent, na.rm = TRUE))

g1 <- ggplot(anes %>% filter(r1 ==1), aes(x=resent)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)*100), fill = "#FC009C", color = "black") + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("Black Resentment Scale") + ylab("Percent of Respondents") + 
  ggtitle("White Born Again Protestants") +
  theme(plot.title = element_text(hjust = 0.5)) + geom_vline(xintercept = .739, linetype =2)

g2 <- ggplot(anes %>% filter(r2 ==2), aes(x=resent)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)*100), fill = "#674E60", color = "black") + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("Black Resentment Scale") + ylab("Percent of Respondents") + 
  ggtitle("White Non Born Again Protestants") +
  theme(plot.title = element_text(hjust = 0.5)) + geom_vline(xintercept = .648, linetype =2)

g3 <- ggplot(anes %>% filter(r4 ==4), aes(x=resent)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)*100), fill = "#365D25", color = "black") + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("Black Resentment Scale") + ylab("Percent of Respondents") + 
  ggtitle("White Catholics") +
  theme(plot.title = element_text(hjust = 0.5)) + geom_vline(xintercept = .678, linetype =2)

g4 <- ggplot(anes %>% filter(white ==1), aes(x=resent)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)*100), fill = "grey", color = "black") + 
  theme(text=element_text(size=18, family="KerkisSans")) + xlab("Black Resentment Scale") + ylab("Percent of Respondents") + 
  ggtitle("Entire White Sample") +
  theme(plot.title = element_text(hjust = 0.5)) + geom_vline(xintercept = .661, linetype =2)

grid.arrange(g1, g2, g3, g4, ncol =1)



```